/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.muraviev;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args){

    }
}
